language: node_js

node_js:
  - 'stable'

cache:
  npm: false

install:
  - npm ci

jobs:
  include:
    - stage: Produce Coverage && run test && run lint
      node_js: node
      script:
        - npm run lint
        - npm run test
        - npm run test:package && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
        # - npm run test:example && cd Example && cat ./coverage/lcov.info  | ../node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
        # - npm run test:ci
